(() => {
  if (globalThis.DivSnapI18n) return;
  const messages = {
    "zh-Hant": {
      languageToggle: "切換為英文", languageToggleShort: "EN", panel: "DivSnap 頁內控制面板", panelTitle: "DivSnap 控制面板", dragPanel: "拖曳移動 DivSnap 控制面板", expandPanel: "展開 DivSnap 控制面板", expand: "展開", resizePanel: "縮放 DivSnap 面板",
      shortcutSettings: "快捷鍵設定", shortcutSettingsTitle: "開啟瀏覽器快捷鍵設定", shortcutUnset: "啟動選取：未設定", shortcutSet: "啟動選取：{shortcut}", shortcutAria: "啟動選取快捷鍵：{shortcut}", unset: "未設定",
      closePanel: "關閉 DivSnap 面板", closePanelTitle: "關閉（連按兩下 Esc）", boundPage: "綁定頁面", unboundPage: "尚未綁定網頁分頁", clickExtension: "請從網頁分頁點擊 DivSnap 圖示。", profile: "Profile", profileUnit: "只保存選取範圍", workspace: "選取工作區", workspaceUnit: "DOM 參照留在頁面", output: "輸出設定", outputUnit: "本次擷取固定設定",
      load: "載入", create: "新增", update: "更新", rename: "重新命名", delete: "刪除", profileEmpty: "目前頁面沒有 Profile", chooseProfile: "選取 Profile", profileName: "Profile 名稱", profilePlaceholder: "手動輸入名稱", profileHint: "載入後會先解析並預覽，不會自動截圖。", profileResolved: "已解析 Profile；問題項目需補選或明確略過。", startInspect: "開始選取", pauseInspect: "暫停選取", unlock: "解鎖預覽", undo: "撤銷", clear: "清除", candidates: "候選層級與重疊元素", notStarted: "尚未開始選取", parent: "↑ 父層", child: "↓ 子層", toggleCurrent: "加入／移除目前項目", selectionList: "已選清單", selectionEmpty: "鎖定預覽或用 Shift＋點擊加入元素。", items: "{count} 項", remove: "移除", dismiss: "略過", directoryGranted: "File System Access · 已授權", directoryDenied: "權限失效，請重新授權", directoryNeedsAuthorization: "需要重新授權後才能寫入",
      visibleDetail: "目前可見範圍", fullDetail: "拼接完整 layout box", pngDetail: "無損，預設格式", webpDetail: "無損格式", copy: "複製到剪貼簿", copyDetail: "固定使用 PNG", save: "儲存圖片", saveDetail: "未選資料夾時使用瀏覽器 Downloads", downloads: "瀏覽器 Downloads", noDirectory: "尚未選擇本機資料夾", chooseDirectory: "選擇資料夾", reauthorize: "重新授權", capture: "CAPTURE", ready: "準備就緒", saveImage: "儲存圖片", retryCopy: "點擊複製 PNG", retryOutput: "重試儲存", footer: "拖曳 DivSnap 標題移動 · 連按兩下 Esc 關閉",
      settingsTitle: "DivSnap 資料夾設定", settingsDescription: "選擇資料夾後，截圖會直接寫入該位置。", directoryNone: "尚未選擇資料夾", directoryPermissionNone: "尚未取得資料夾權限", chooseCurrent: "選擇資料夾", reauthorizeCurrent: "重新授權目前資料夾", directoryRemembered: "已記住設定，按重新授權確認寫入權限", directoryUpdated: "資料夾已更新。", directoryPermissionMissing: "資料夾權限仍未授予。",
      initializing: "初始化失敗：{error}", profileReadFailed: "Profile 讀取失敗：{error}", targetLoading: "目標分頁正在重新載入，請等待狀態更新。", outputFailed: "輸出失敗：{error}", outputDisabled: "請至少開啟一種輸出方式。", capturing: "正在擷取…", processingOutput: "正在處理輸出…", captureFailed: "截圖失敗：{error}", unknownError: "未知錯誤", copying: "正在複製…", retryingSave: "正在重試儲存…", webpFailed: "WebP 編碼失敗：{error}", clipboardFailed: "剪貼簿複製失敗：{error}", saved: "已儲存 {filename}", sentDownloads: "已送至瀏覽器 Downloads", saveFailed: "{action}失敗：{error}", saving: "儲存", downloading: "下載", selectionKept: "已保留選取。", invalid: "失效 · ", enterProfile: "請先輸入 Profile 名稱。", enterNewProfile: "請先輸入新的 Profile 名稱。", selectElement: "請先選取至少一個有效元素。", profileCreated: "Profile「{name}」已新增。", profileRenamed: "Profile 已重新命名為「{name}」。", profileUpdated: "Profile「{name}」已更新。", deleteProfile: "刪除 Profile「{name}」？", profileDeleted: "Profile 已刪除。", openedDirectory: "已開啟資料夾設定分頁。", shortcutOpenFailed: "無法開啟快捷鍵設定：{error}", openDirectoryFailed: "無法開啟資料夾設定：{error}", folderUnsupported: "目前瀏覽器不支援選擇資料夾。", chooseFolderFailed: "選擇資料夾失敗：{error}", chooseCancelled: "已取消選擇，原設定保留。", noFolderToAuthorize: "目前沒有可重新授權的資料夾，請先選擇資料夾。", reauthorizeFailed: "重新授權失敗：{error}", returning: "已更新，正在返回原網頁。", retainedNeedsAuthorization: "設定已保留，但仍需要重新授權。", settingsUpdateFailed: "設定更新失敗。",
      locked: "已鎖定 · ", selectedStatus: "已選 {count} 項 · {state} · 外接矩形包含框內所有內容", previewLocked: "預覽已鎖定", hoverPreview: "滑過僅預覽", targetInvalid: "目標已失效：請移除或重新選取後截圖。", profileUnresolved: "Profile 尚有缺失、重複或待確認項目。", inspectorStopped: "Inspector 已停止。", captureRuntimeFailed: "截圖失敗：{error}", visibleClipped: "Visible crop / 已裁切至可見範圍", fullTooLarge: "Full exceeds 8192px / 超過限制，改用 Visible", resolutionMissing: "缺失", resolutionAmbiguous: "多重命中", resolutionConfirm: "待確認", resolutionPending: "待處理", activeTabMissing: "找不到目前分頁。", pageUnavailable: "目前頁面無法啟動 DivSnap。", panelOpenFailed: "無法開啟頁內面板。", panelRecreateFailed: "無法重新建立頁內面板。", sessionChanged: "工作階段已更新，請重新選取分頁。", noBoundTab: "尚未綁定網頁分頁。", targetTabMissing: "找不到目標分頁。", directoryNotSelected: "尚未選擇本機資料夾。", directoryExpired: "資料夾權限失效，請先按「重新授權」。", filenameUnavailable: "找不到可用檔名。", controlDisconnected: "控制面板連線已失效。"
    },
    en: {
      languageToggle: "Switch to Traditional Chinese", languageToggleShort: "中", panel: "DivSnap in-page control panel", panelTitle: "DivSnap control panel", dragPanel: "Drag to move DivSnap control panel", expandPanel: "Expand DivSnap control panel", expand: "Expand", resizePanel: "Resize DivSnap panel",
      shortcutSettings: "Shortcuts", shortcutSettingsTitle: "Open browser shortcut settings", shortcutUnset: "Start inspect: unset", shortcutSet: "Start inspect: {shortcut}", shortcutAria: "Start inspect shortcut: {shortcut}", unset: "unset",
      closePanel: "Close DivSnap panel", closePanelTitle: "Close (press Escape twice)", boundPage: "BOUND PAGE", unboundPage: "No web tab bound", clickExtension: "Click the DivSnap icon from a web tab.", profile: "Profile", profileUnit: "Saves selected targets only", workspace: "SELECTION", workspaceUnit: "DOM references stay on the page", output: "OUTPUT", outputUnit: "Used for this capture", load: "Load", create: "New", update: "Update", rename: "Rename", delete: "Delete", profileEmpty: "No Profile for this page", chooseProfile: "Select Profile", profileName: "Profile name", profilePlaceholder: "Enter a name", profileHint: "Loading resolves and previews targets; it does not capture automatically.", profileResolved: "Profile resolved; repair or dismiss any issue below.", startInspect: "Start inspect", pauseInspect: "Pause inspect", unlock: "Unlock preview", undo: "Undo", clear: "Clear", candidates: "Candidate levels and overlapping elements", notStarted: "Inspection has not started", parent: "↑ Parent", child: "↓ Child", toggleCurrent: "Add / remove current", selectionList: "SELECTED", selectionEmpty: "Lock a preview or Shift-click to add an element.", items: "{count} item(s)", remove: "Remove", dismiss: "Dismiss", directoryGranted: "File System Access · granted", directoryDenied: "Permission expired; reauthorize", directoryNeedsAuthorization: "Reauthorize before writing",
      visibleDetail: "Current visible area", fullDetail: "Stitch the full layout box", pngDetail: "Lossless, default format", webpDetail: "Lossless format", copy: "Copy to clipboard", copyDetail: "Always uses PNG", save: "Save image", saveDetail: "Uses browser Downloads without a folder", downloads: "Browser Downloads", noDirectory: "No local folder selected", chooseDirectory: "Choose folder", reauthorize: "Reauthorize", capture: "CAPTURE", ready: "Ready", saveImage: "Save image", retryCopy: "Copy PNG", retryOutput: "Retry save", footer: "Drag the DivSnap title to move · Press Escape twice to close",
      settingsTitle: "DivSnap folder settings", settingsDescription: "Screenshots are written directly to the selected folder.", directoryNone: "No folder selected", directoryPermissionNone: "Folder permission has not been granted", chooseCurrent: "Choose folder", reauthorizeCurrent: "Reauthorize current folder", directoryRemembered: "Setting remembered; reauthorize to confirm write access", directoryUpdated: "Folder updated.", directoryPermissionMissing: "Folder permission is still not granted.",
      initializing: "Initialization failed: {error}", profileReadFailed: "Could not read Profiles: {error}", targetLoading: "The target tab is reloading. Wait for its status to update.", outputFailed: "Output failed: {error}", outputDisabled: "Enable at least one output option.", capturing: "Capturing…", processingOutput: "Processing output…", captureFailed: "Capture failed: {error}", unknownError: "Unknown error", copying: "Copying…", retryingSave: "Retrying save…", webpFailed: "WebP encoding failed: {error}", clipboardFailed: "Clipboard copy failed: {error}", saved: "Saved {filename}", sentDownloads: "Sent to browser Downloads", saveFailed: "{action} failed: {error}", saving: "Save", downloading: "Download", selectionKept: "Selection retained.", invalid: "Invalid · ", enterProfile: "Enter a Profile name first.", enterNewProfile: "Enter a new Profile name first.", selectElement: "Select at least one valid element first.", profileCreated: "Profile “{name}” created.", profileRenamed: "Profile renamed to “{name}”.", profileUpdated: "Profile “{name}” updated.", deleteProfile: "Delete Profile “{name}”?", profileDeleted: "Profile deleted.", openedDirectory: "Folder settings opened.", shortcutOpenFailed: "Could not open shortcut settings: {error}", openDirectoryFailed: "Could not open folder settings: {error}", folderUnsupported: "This browser does not support folder selection.", chooseFolderFailed: "Could not choose folder: {error}", chooseCancelled: "Selection cancelled; the current setting was kept.", noFolderToAuthorize: "No folder can be reauthorized; choose one first.", reauthorizeFailed: "Reauthorization failed: {error}", returning: "Updated. Returning to the original page.", retainedNeedsAuthorization: "Setting retained, but reauthorization is still required.", settingsUpdateFailed: "Could not update settings.",
      locked: "Locked · ", selectedStatus: "{count} selected · {state} · the union rectangle includes all enclosed content", previewLocked: "preview locked", hoverPreview: "hover preview", targetInvalid: "Target is invalid. Remove it or select it again before capturing.", profileUnresolved: "Profile has missing, duplicate, or unconfirmed targets.", inspectorStopped: "Inspector stopped.", captureRuntimeFailed: "Capture failed: {error}", visibleClipped: "Visible crop / clipped to the visible area", fullTooLarge: "Full exceeds 8192px; switched to Visible", resolutionMissing: "Missing", resolutionAmbiguous: "Multiple matches", resolutionConfirm: "Needs confirmation", resolutionPending: "Pending", activeTabMissing: "Active tab unavailable.", pageUnavailable: "DivSnap cannot start on this page.", panelOpenFailed: "Could not open the in-page panel.", panelRecreateFailed: "Could not recreate the in-page panel.", sessionChanged: "Session changed. Select the tab again.", noBoundTab: "No web tab is bound.", targetTabMissing: "Target tab unavailable.", directoryNotSelected: "No local folder selected.", directoryExpired: "Folder permission expired. Reauthorize it first.", filenameUnavailable: "No available filename found.", controlDisconnected: "Control panel connection was lost."
    }
  };

  const normalize = (language) => language === "en" ? "en" : "zh-Hant";
  let language = "zh-Hant";
  const extensionDocument = typeof document !== "undefined" && typeof location !== "undefined" && /-extension:$/.test(location.protocol);
  const t = (key, values = {}) => (messages[language][key] || messages["zh-Hant"][key] || key).replace(/\{(\w+)\}/g, (_, name) => String(values[name] ?? ""));
  const apply = (root = typeof document === "undefined" ? null : document) => {
    if (!extensionDocument) return;
    document.documentElement.lang = language;
    root.querySelectorAll?.("[data-i18n]").forEach((element) => { element.textContent = t(element.dataset.i18n); });
    root.querySelectorAll?.("[data-i18n-title]").forEach((element) => { element.title = t(element.dataset.i18nTitle); });
    root.querySelectorAll?.("[data-i18n-aria-label]").forEach((element) => { element.setAttribute("aria-label", t(element.dataset.i18nAriaLabel)); });
    root.querySelectorAll?.("[data-i18n-placeholder]").forEach((element) => { element.placeholder = t(element.dataset.i18nPlaceholder); });
  };
  async function load() {
    const stored = await chrome.storage.sync.get({language: "zh-Hant"});
    language = normalize(stored.language);
    apply();
    return language;
  }
  async function set(next) {
    language = normalize(next);
    await chrome.storage.sync.set({language});
    apply();
    return language;
  }
  chrome.storage?.onChanged?.addListener((changes, area) => {
    if (area !== "sync" || !changes.language) return;
    language = normalize(changes.language.newValue);
    apply();
    globalThis.DivSnapI18n?.onChange?.forEach((listener) => listener(language));
  });
  globalThis.DivSnapI18n = {t, apply, load, set, get language() { return language; }, onChange: new Set()};
})();
